### ISSUE TITLE
Multiple instances per page

### ISSUE THREAD

**Issue by Comp0ser** [osvaldasvalutis/imageLightbox.js#1]
Right now it seems not possible (without unexpected errors) to instance and use multiple lightboxes on one page.

**Comment by osvaldasvalutis** [comment]
It's possible and always been. Check the source code of the [demo page](https://osvaldas.info/examples/image-lightbox-responsive-touch-friendly). Here's a hint:

```
<a href="animal-1.jpg" class="animals">Animal 1</a>
<a href="animal-2.jpg" class="animals">Animal 2</a>
...
$( '.animals' ).imageLightbox();

<a href="portrait-1.jpg" class="portraits">Portrait 1</a>
<a href="portrait-2.jpg" class="portraits"> Portrait 2</a>
...
$( '.portraits' ).imageLightbox();
```
